# Generated by Django 5.2.8 on 2025-11-17 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securefile',
            name='shared_token',
        ),
        migrations.AddField(
            model_name='securefile',
            name='aes_key_owner_wrapped',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WrappedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_keys', to='files_app.securefile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'recipient')},
            },
        ),
    ]
