# Generated by Django 5.2.8 on 2025-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_remove_securefile_shared_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='aes_key_owner_wrapped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securefile',
            name='iv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
