# Generated by Django 5.2.8 on 2025-11-21 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0004_alter_securefile_owner_storedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='aes_key_owner_wrapped',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='securefile',
            name='iv',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='wrappedkey',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StoredFile',
        ),
    ]
