# Generated by Django 4.2.13 on 2026-05-09 08:54

from django.db import migrations, models
from pathlib import Path


CATEGORY_EXTENSIONS = {
    "pdfs": {".pdf"},
    "photos": {".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".heic", ".heif", ".bmp", ".tif", ".tiff", ".svg"},
    "videos": {".mp4", ".mov", ".m4v", ".webm", ".avi", ".mkv", ".wmv"},
    "audio": {".mp3", ".wav", ".m4a", ".flac", ".aac", ".ogg"},
    "archives": {".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz"},
    "spreadsheets": {".xls", ".xlsx", ".csv", ".ods", ".numbers"},
    "presentations": {".ppt", ".pptx", ".odp", ".key"},
    "code": {
        ".js", ".jsx", ".ts", ".tsx", ".py", ".java", ".cs", ".go", ".rs", ".rb", ".php",
        ".html", ".css", ".json", ".xml", ".yml", ".yaml", ".sql", ".sh", ".ps1",
    },
    "documents": {".doc", ".docx", ".txt", ".rtf", ".odt", ".md", ".pages"},
}


def backfill_file_categories(apps, schema_editor):
    SecureFile = apps.get_model("files_app", "SecureFile")
    for file_obj in SecureFile.objects.all().only("id", "original_name"):
        extension = Path(file_obj.original_name or "").suffix.lower()[:24]
        category = "other"
        for candidate, extensions in CATEGORY_EXTENSIONS.items():
            if extension in extensions:
                category = candidate
                break
        file_obj.category = category
        file_obj.extension = extension
        file_obj.save(update_fields=["category", "extension"])


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0009_alter_securefile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='category',
            field=models.CharField(choices=[('documents', 'Documents'), ('pdfs', 'PDFs'), ('photos', 'Photos'), ('videos', 'Videos'), ('audio', 'Audio'), ('archives', 'Archives'), ('spreadsheets', 'Spreadsheets'), ('presentations', 'Presentations'), ('code', 'Code'), ('other', 'Other')], db_index=True, default='other', max_length=24),
        ),
        migrations.AddField(
            model_name='securefile',
            name='extension',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.RunPython(backfill_file_categories, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='securefile',
            index=models.Index(fields=['owner', 'category'], name='files_owner_category_idx'),
        ),
    ]
